# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainManufacturerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManufacturerWindow(object):
    def setupUi(self, ManufacturerWindow):
        ManufacturerWindow.setObjectName("ManufacturerWindow")
        ManufacturerWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(ManufacturerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.background.setStyleSheet("#background{\n"
"border-radius:7px;\n"
"background-color: rgb(38, 38, 38);\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.main_2 = QtWidgets.QFrame(self.background)
        self.main_2.setGeometry(QtCore.QRect(0, 63, 1024, 642))
        self.main_2.setStyleSheet("background-color: rgb(59, 59, 89);")
        self.main_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_2.setObjectName("main_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1022, 640))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Mainwindow = QtWidgets.QWidget()
        self.page_Mainwindow.setObjectName("page_Mainwindow")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.page_Mainwindow)
        self.scrollArea_6.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setMinimumSize(QtCore.QSize(781, 454))
        self.scrollArea_6.setStyleSheet("QProgressBar{\n"
"background-color: white; \n"
"border: 1px solid black;\n"
"}")
        self.scrollArea_6.setWidgetResizable(False)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollArea_7 = QtWidgets.QWidget()
        self.scrollArea_7.setGeometry(QtCore.QRect(0, 0, 1024, 753))
        self.scrollArea_7.setMinimumSize(QtCore.QSize(766, 0))
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.homepage = QtWidgets.QFrame(self.scrollArea_7)
        self.homepage.setGeometry(QtCore.QRect(0, 0, 1024, 171))
        self.homepage.setMinimumSize(QtCore.QSize(771, 120))
        self.homepage.setStyleSheet("background-color: rgb(101, 222, 255);")
        self.homepage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.homepage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.homepage.setObjectName("homepage")
        self.HPTitle = QtWidgets.QLabel(self.homepage)
        self.HPTitle.setGeometry(QtCore.QRect(380, 110, 291, 31))
        self.HPTitle.setStyleSheet("background-color: rgba(0, 0, 0，0);  \n"
"font: 18pt \"华文彩云\";\n"
"color: rgb(255, 255, 255);")
        self.HPTitle.setObjectName("HPTitle")
        self.listView = QtWidgets.QListView(self.scrollArea_7)
        self.listView.setGeometry(QtCore.QRect(235, 220, 540, 291))
        self.listView.setObjectName("listView")
        self.lable_Title = QtWidgets.QLabel(self.scrollArea_7)
        self.lable_Title.setGeometry(QtCore.QRect(410, 240, 231, 31))
        self.lable_Title.setStyleSheet("background-color: rgba(0, 0, 0，0);  \n"
"font: 18pt \"华文彩云\";\n"
"color: rgb(255, 255, 255);")
        self.lable_Title.setObjectName("lable_Title")
        self.lable_manufacturerID = QtWidgets.QLabel(self.scrollArea_7)
        self.lable_manufacturerID.setGeometry(QtCore.QRect(340, 310, 54, 12))
        self.lable_manufacturerID.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 10pt \"华光胖头鱼_CNKI\";")
        self.lable_manufacturerID.setObjectName("lable_manufacturerID")
        self.lable_manufacturerGameSum = QtWidgets.QLabel(self.scrollArea_7)
        self.lable_manufacturerGameSum.setGeometry(QtCore.QRect(340, 370, 54, 12))
        self.lable_manufacturerGameSum.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 10pt \"华光胖头鱼_CNKI\";")
        self.lable_manufacturerGameSum.setObjectName("lable_manufacturerGameSum")
        self.message1 = QtWidgets.QLabel(self.scrollArea_7)
        self.message1.setGeometry(QtCore.QRect(430, 310, 191, 16))
        self.message1.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 10pt \"华光胖头鱼_CNKI\";")
        self.message1.setText("")
        self.message1.setObjectName("message1")
        self.message3 = QtWidgets.QLabel(self.scrollArea_7)
        self.message3.setGeometry(QtCore.QRect(430, 370, 201, 16))
        self.message3.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 10pt \"华光胖头鱼_CNKI\";")
        self.message3.setText("")
        self.message3.setObjectName("message3")
        self.scrollArea_6.setWidget(self.scrollArea_7)
        self.stackedWidget.addWidget(self.page_Mainwindow)
        self.page_releaseGame = QtWidgets.QWidget()
        self.page_releaseGame.setObjectName("page_releaseGame")
        self.frame = QtWidgets.QFrame(self.page_releaseGame)
        self.frame.setGeometry(QtCore.QRect(200, 99, 622, 471))
        self.frame.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255,80);\n"
"border: none\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255,80);\n"
"border: none\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_gameName = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_gameName.setGeometry(QtCore.QRect(30, 10, 561, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_gameName.sizePolicy().hasHeightForWidth())
        self.lineEdit_gameName.setSizePolicy(sizePolicy)
        self.lineEdit_gameName.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_gameName.setStyleSheet("")
        self.lineEdit_gameName.setText("")
        self.lineEdit_gameName.setObjectName("lineEdit_gameName")
        self.lineEdit_gameType1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_gameType1.setGeometry(QtCore.QRect(424, 360, 166, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_gameType1.sizePolicy().hasHeightForWidth())
        self.lineEdit_gameType1.setSizePolicy(sizePolicy)
        self.lineEdit_gameType1.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_gameType1.setObjectName("lineEdit_gameType1")
        self.lineEdit_gamePrice = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_gamePrice.setGeometry(QtCore.QRect(30, 420, 561, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_gamePrice.sizePolicy().hasHeightForWidth())
        self.lineEdit_gamePrice.setSizePolicy(sizePolicy)
        self.lineEdit_gamePrice.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_gamePrice.setObjectName("lineEdit_gamePrice")
        self.lineEdit_gameType3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_gameType3.setGeometry(QtCore.QRect(30, 360, 167, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_gameType3.sizePolicy().hasHeightForWidth())
        self.lineEdit_gameType3.setSizePolicy(sizePolicy)
        self.lineEdit_gameType3.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_gameType3.setObjectName("lineEdit_gameType3")
        self.lineEdit_gameType2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_gameType2.setGeometry(QtCore.QRect(227, 360, 167, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_gameType2.sizePolicy().hasHeightForWidth())
        self.lineEdit_gameType2.setSizePolicy(sizePolicy)
        self.lineEdit_gameType2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_gameType2.setObjectName("lineEdit_gameType2")
        self.textEdit_gameIntroduction = QtWidgets.QTextEdit(self.frame)
        self.textEdit_gameIntroduction.setGeometry(QtCore.QRect(30, 100, 561, 241))
        self.textEdit_gameIntroduction.setObjectName("textEdit_gameIntroduction")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(30, 69, 561, 31))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.frame_9 = QtWidgets.QFrame(self.page_releaseGame)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 1024, 70))
        self.frame_9.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        self.label_2.setGeometry(QtCore.QRect(411, 20, 200, 31))
        self.label_2.setStyleSheet("font: 20pt \"华文琥珀\";\n"
"background-color: rgb(255, 255, 255，100);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_releaseSure = QtWidgets.QPushButton(self.page_releaseGame)
        self.pushButton_releaseSure.setGeometry(QtCore.QRect(230, 590, 171, 31))
        self.pushButton_releaseSure.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_releaseSure.setObjectName("pushButton_releaseSure")
        self.success_error_Type = QtWidgets.QStackedWidget(self.page_releaseGame)
        self.success_error_Type.setGeometry(QtCore.QRect(420, 590, 220, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.success_error_Type.sizePolicy().hasHeightForWidth())
        self.success_error_Type.setSizePolicy(sizePolicy)
        self.success_error_Type.setStyleSheet("#successLogIn{\n"
"}\n"
"#successRegister{\n"
"}\n"
"#sizeWrong{\n"
"    color: rgb(190, 0, 0);\n"
"}\n"
"#userNameWrong{\n"
"    color: rgb(190, 0, 0);\n"
"}\n"
"#passwordWrong{\n"
"    color: rgb(190, 0, 0);\n"
"}\n"
"#logInWrong{\n"
"    color: rgb(190, 0, 0);\n"
"}")
        self.success_error_Type.setObjectName("success_error_Type")
        self.emptyPage = QtWidgets.QWidget()
        self.emptyPage.setObjectName("emptyPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.emptyPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.success_error_Type.addWidget(self.emptyPage)
        self.page_success = QtWidgets.QWidget()
        self.page_success.setObjectName("page_success")
        self.successRelease = QtWidgets.QLabel(self.page_success)
        self.successRelease.setGeometry(QtCore.QRect(0, 10, 54, 12))
        self.successRelease.setStyleSheet("color: rgb(255, 255, 255);")
        self.successRelease.setObjectName("successRelease")
        self.success_error_Type.addWidget(self.page_success)
        self.page_error1 = QtWidgets.QWidget()
        self.page_error1.setObjectName("page_error1")
        self.successRelease_2 = QtWidgets.QLabel(self.page_error1)
        self.successRelease_2.setGeometry(QtCore.QRect(0, 10, 111, 12))
        self.successRelease_2.setStyleSheet("color: rgb(190, 0, 0);")
        self.successRelease_2.setObjectName("successRelease_2")
        self.success_error_Type.addWidget(self.page_error1)
        self.page_error2 = QtWidgets.QWidget()
        self.page_error2.setObjectName("page_error2")
        self.successRelease_3 = QtWidgets.QLabel(self.page_error2)
        self.successRelease_3.setGeometry(QtCore.QRect(0, 10, 111, 12))
        self.successRelease_3.setStyleSheet("color: rgb(190, 0, 0);")
        self.successRelease_3.setObjectName("successRelease_3")
        self.success_error_Type.addWidget(self.page_error2)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout = QtWidgets.QGridLayout(self.page1)
        self.gridLayout.setObjectName("gridLayout")
        self.successLogIn = QtWidgets.QLabel(self.page1)
        self.successLogIn.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.successLogIn.setObjectName("successLogIn")
        self.gridLayout.addWidget(self.successLogIn, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.successRegister = QtWidgets.QLabel(self.page2)
        self.successRegister.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.successRegister.setObjectName("successRegister")
        self.horizontalLayout_3.addWidget(self.successRegister, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.logInWrong = QtWidgets.QLabel(self.page3)
        self.logInWrong.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.logInWrong.setObjectName("logInWrong")
        self.verticalLayout_7.addWidget(self.logInWrong, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sizeWrong = QtWidgets.QLabel(self.page4)
        self.sizeWrong.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.sizeWrong.setObjectName("sizeWrong")
        self.verticalLayout_9.addWidget(self.sizeWrong, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.userNameWrong = QtWidgets.QLabel(self.page5)
        self.userNameWrong.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.userNameWrong.setObjectName("userNameWrong")
        self.verticalLayout_10.addWidget(self.userNameWrong, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page5)
        self.page6 = QtWidgets.QWidget()
        self.page6.setObjectName("page6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.passwordWrong = QtWidgets.QLabel(self.page6)
        self.passwordWrong.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.passwordWrong.setObjectName("passwordWrong")
        self.verticalLayout_11.addWidget(self.passwordWrong, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page6)
        self.stackedWidget.addWidget(self.page_releaseGame)
        self.page_GameGarage = QtWidgets.QWidget()
        self.page_GameGarage.setObjectName("page_GameGarage")
        self.frame_14 = QtWidgets.QFrame(self.page_GameGarage)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 1024, 180))
        self.frame_14.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton_10.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton_10.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/u=157358869,2307745509&fm=217&app=126&size=f242,150&n=0&f=PNG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(320, 320))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_Show_UserName_4 = QtWidgets.QLabel(self.frame_14)
        self.label_Show_UserName_4.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_UserName_4.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_UserName_4.setText("")
        self.label_Show_UserName_4.setObjectName("label_Show_UserName_4")
        self.label = QtWidgets.QLabel(self.frame_14)
        self.label.setGeometry(QtCore.QRect(460, 130, 251, 51))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0，0);  \n"
"font: 18pt \"华文彩云\";\n"
"color: rgb(255, 255, 255);\n"
"    ")
        self.label.setObjectName("label")
        self.scrollArea_8 = QtWidgets.QScrollArea(self.page_GameGarage)
        self.scrollArea_8.setGeometry(QtCore.QRect(200, 210, 821, 431))
        self.scrollArea_8.setWidgetResizable(False)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 806, 800))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_5)
        self.pushButton_UnsetGames = QtWidgets.QPushButton(self.page_GameGarage)
        self.pushButton_UnsetGames.setGeometry(QtCore.QRect(30, 310, 151, 23))
        self.pushButton_UnsetGames.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_UnsetGames.setObjectName("pushButton_UnsetGames")
        self.pushButton_SettedGames = QtWidgets.QPushButton(self.page_GameGarage)
        self.pushButton_SettedGames.setGeometry(QtCore.QRect(30, 270, 151, 23))
        self.pushButton_SettedGames.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_SettedGames.setObjectName("pushButton_SettedGames")
        self.pushButton_AllGames = QtWidgets.QPushButton(self.page_GameGarage)
        self.pushButton_AllGames.setGeometry(QtCore.QRect(30, 230, 151, 23))
        self.pushButton_AllGames.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_AllGames.setObjectName("pushButton_AllGames")
        self.listWidget_4 = QtWidgets.QListWidget(self.page_GameGarage)
        self.listWidget_4.setGeometry(QtCore.QRect(0, 210, 200, 140))
        self.listWidget_4.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.listWidget_4.setObjectName("listWidget_4")
        self.menu_4 = QtWidgets.QFrame(self.page_GameGarage)
        self.menu_4.setGeometry(QtCore.QRect(0, 705, 1024, 54))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.menu_4.sizePolicy().hasHeightForWidth())
        self.menu_4.setSizePolicy(sizePolicy)
        self.menu_4.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.menu_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_4.setObjectName("menu_4")
        self.searchbar_2 = QtWidgets.QFrame(self.page_GameGarage)
        self.searchbar_2.setGeometry(QtCore.QRect(280, 180, 661, 30))
        self.searchbar_2.setStyleSheet("#frame{\n"
"background-color: rgb(59, 59, 89,0.2);\n"
"border-radius:15px;\n"
"}")
        self.searchbar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchbar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchbar_2.setObjectName("searchbar_2")
        self.searchline_2 = QtWidgets.QLineEdit(self.searchbar_2)
        self.searchline_2.setGeometry(QtCore.QRect(240, 0, 125, 30))
        self.searchline_2.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);\n"
"    border: none;")
        self.searchline_2.setObjectName("searchline_2")
        self.searchButton_3 = QtWidgets.QPushButton(self.searchbar_2)
        self.searchButton_3.setGeometry(QtCore.QRect(365, 0, 40, 30))
        self.searchButton_3.setStyleSheet("background-color: rgb(255, 255, 255，0);\n"
"border:none")
        self.searchButton_3.setText("")
        self.searchButton_3.setObjectName("searchButton_3")
        self.listWidget_4.raise_()
        self.frame_14.raise_()
        self.scrollArea_8.raise_()
        self.pushButton_UnsetGames.raise_()
        self.pushButton_SettedGames.raise_()
        self.pushButton_AllGames.raise_()
        self.menu_4.raise_()
        self.searchbar_2.raise_()
        self.stackedWidget.addWidget(self.page_GameGarage)
        self.page_FollowUsers = QtWidgets.QWidget()
        self.page_FollowUsers.setObjectName("page_FollowUsers")
        self.frame_15 = QtWidgets.QFrame(self.page_FollowUsers)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 1024, 180))
        self.frame_15.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton_11.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(320, 320))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_Show_UserName_5 = QtWidgets.QLabel(self.frame_15)
        self.label_Show_UserName_5.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_UserName_5.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_UserName_5.setText("")
        self.label_Show_UserName_5.setObjectName("label_Show_UserName_5")
        self.label_5 = QtWidgets.QLabel(self.frame_15)
        self.label_5.setGeometry(QtCore.QRect(460, 130, 270, 50))
        self.label_5.setStyleSheet("background-color: rgba(0, 0, 0，0);  \n"
"font: 18pt \"华文彩云\";\n"
"color: rgb(255, 255, 255);\n"
"    ")
        self.label_5.setObjectName("label_5")
        self.searchbar_3 = QtWidgets.QFrame(self.page_FollowUsers)
        self.searchbar_3.setGeometry(QtCore.QRect(280, 180, 661, 30))
        self.searchbar_3.setStyleSheet("#frame{\n"
"background-color: rgb(59, 59, 89,0.2);\n"
"border-radius:15px;\n"
"}")
        self.searchbar_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchbar_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchbar_3.setObjectName("searchbar_3")
        self.searchline_3 = QtWidgets.QLineEdit(self.searchbar_3)
        self.searchline_3.setGeometry(QtCore.QRect(240, 0, 125, 30))
        self.searchline_3.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);\n"
"    border: none;")
        self.searchline_3.setObjectName("searchline_3")
        self.searchButton_4 = QtWidgets.QPushButton(self.searchbar_3)
        self.searchButton_4.setGeometry(QtCore.QRect(365, 0, 40, 30))
        self.searchButton_4.setStyleSheet("background-color: rgb(255, 255, 255，0);\n"
"border:none")
        self.searchButton_4.setText("")
        self.searchButton_4.setObjectName("searchButton_4")
        self.pushButton_FollowedUSR = QtWidgets.QPushButton(self.page_FollowUsers)
        self.pushButton_FollowedUSR.setGeometry(QtCore.QRect(30, 230, 151, 23))
        self.pushButton_FollowedUSR.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_FollowedUSR.setObjectName("pushButton_FollowedUSR")
        self.listWidget_5 = QtWidgets.QListWidget(self.page_FollowUsers)
        self.listWidget_5.setGeometry(QtCore.QRect(0, 210, 200, 121))
        self.listWidget_5.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.listWidget_5.setObjectName("listWidget_5")
        self.pushButton_UnfollowedUSR = QtWidgets.QPushButton(self.page_FollowUsers)
        self.pushButton_UnfollowedUSR.setGeometry(QtCore.QRect(30, 280, 151, 23))
        self.pushButton_UnfollowedUSR.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_UnfollowedUSR.setObjectName("pushButton_UnfollowedUSR")
        self.scrollArea_10 = QtWidgets.QScrollArea(self.page_FollowUsers)
        self.scrollArea_10.setGeometry(QtCore.QRect(200, 210, 821, 431))
        self.scrollArea_10.setWidgetResizable(False)
        self.scrollArea_10.setObjectName("scrollArea_10")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 806, 800))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_6)
        self.listWidget_5.raise_()
        self.frame_15.raise_()
        self.searchbar_3.raise_()
        self.pushButton_FollowedUSR.raise_()
        self.pushButton_UnfollowedUSR.raise_()
        self.scrollArea_10.raise_()
        self.stackedWidget.addWidget(self.page_FollowUsers)
        self.page_ShopList = QtWidgets.QWidget()
        self.page_ShopList.setObjectName("page_ShopList")
        self.frame_16 = QtWidgets.QFrame(self.page_ShopList)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 1024, 180))
        self.frame_16.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton_12.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setIconSize(QtCore.QSize(320, 320))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_Show_UserName_6 = QtWidgets.QLabel(self.frame_16)
        self.label_Show_UserName_6.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_UserName_6.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_UserName_6.setText("")
        self.label_Show_UserName_6.setObjectName("label_Show_UserName_6")
        self.label_8 = QtWidgets.QLabel(self.frame_16)
        self.label_8.setGeometry(QtCore.QRect(460, 130, 270, 50))
        self.label_8.setStyleSheet("background-color: rgba(0, 0, 0，0);  \n"
"font: 18pt \"华文彩云\";\n"
"color: rgb(255, 255, 255);\n"
"    ")
        self.label_8.setObjectName("label_8")
        self.listWidget_6 = QtWidgets.QListWidget(self.page_ShopList)
        self.listWidget_6.setGeometry(QtCore.QRect(0, 210, 200, 121))
        self.listWidget_6.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.listWidget_6.setObjectName("listWidget_6")
        self.searchbar_4 = QtWidgets.QFrame(self.page_ShopList)
        self.searchbar_4.setGeometry(QtCore.QRect(280, 180, 661, 30))
        self.searchbar_4.setStyleSheet("#frame{\n"
"background-color: rgb(59, 59, 89,0.2);\n"
"border-radius:15px;\n"
"}")
        self.searchbar_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchbar_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchbar_4.setObjectName("searchbar_4")
        self.searchline_4 = QtWidgets.QLineEdit(self.searchbar_4)
        self.searchline_4.setGeometry(QtCore.QRect(240, 0, 125, 30))
        self.searchline_4.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);\n"
"    border: none;")
        self.searchline_4.setObjectName("searchline_4")
        self.searchButton_5 = QtWidgets.QPushButton(self.searchbar_4)
        self.searchButton_5.setGeometry(QtCore.QRect(365, 0, 40, 30))
        self.searchButton_5.setStyleSheet("background-color: rgb(255, 255, 255，0);\n"
"border:none")
        self.searchButton_5.setText("")
        self.searchButton_5.setObjectName("searchButton_5")
        self.scrollArea_11 = QtWidgets.QScrollArea(self.page_ShopList)
        self.scrollArea_11.setGeometry(QtCore.QRect(200, 210, 821, 431))
        self.scrollArea_11.setWidgetResizable(False)
        self.scrollArea_11.setObjectName("scrollArea_11")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 806, 800))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_7)
        self.pushButton_PayList = QtWidgets.QPushButton(self.page_ShopList)
        self.pushButton_PayList.setGeometry(QtCore.QRect(20, 230, 151, 23))
        self.pushButton_PayList.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_PayList.setObjectName("pushButton_PayList")
        self.pushButton_PaybackList = QtWidgets.QPushButton(self.page_ShopList)
        self.pushButton_PaybackList.setGeometry(QtCore.QRect(20, 280, 151, 23))
        self.pushButton_PaybackList.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_PaybackList.setObjectName("pushButton_PaybackList")
        self.stackedWidget.addWidget(self.page_ShopList)
        self.page_Comment = QtWidgets.QWidget()
        self.page_Comment.setObjectName("page_Comment")
        self.frame_17 = QtWidgets.QFrame(self.page_Comment)
        self.frame_17.setGeometry(QtCore.QRect(0, 0, 1024, 180))
        self.frame_17.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton_13.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setIconSize(QtCore.QSize(320, 320))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_Show_UserName_7 = QtWidgets.QLabel(self.frame_17)
        self.label_Show_UserName_7.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_UserName_7.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_UserName_7.setText("")
        self.label_Show_UserName_7.setObjectName("label_Show_UserName_7")
        self.label_9 = QtWidgets.QLabel(self.frame_17)
        self.label_9.setGeometry(QtCore.QRect(460, 130, 270, 50))
        self.label_9.setStyleSheet("background-color: rgba(0, 0, 0，0);  \n"
"font: 18pt \"华文彩云\";\n"
"color: rgb(255, 255, 255);\n"
"    ")
        self.label_9.setObjectName("label_9")
        self.listWidget_7 = QtWidgets.QListWidget(self.page_Comment)
        self.listWidget_7.setGeometry(QtCore.QRect(0, 210, 200, 120))
        self.listWidget_7.setStyleSheet("QWidget {\n"
"         background-color:rgb(64, 100, 167);  \n"
"     }")
        self.listWidget_7.setObjectName("listWidget_7")
        self.searchline_Games = QtWidgets.QLineEdit(self.page_Comment)
        self.searchline_Games.setGeometry(QtCore.QRect(20, 230, 160, 20))
        self.searchline_Games.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);\n"
"    border: none;")
        self.searchline_Games.setObjectName("searchline_Games")
        self.searchline_Users = QtWidgets.QLineEdit(self.page_Comment)
        self.searchline_Users.setGeometry(QtCore.QRect(20, 280, 160, 20))
        self.searchline_Users.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);\n"
"    border: none;")
        self.searchline_Users.setObjectName("searchline_Users")
        self.scrollArea_12 = QtWidgets.QScrollArea(self.page_Comment)
        self.scrollArea_12.setGeometry(QtCore.QRect(200, 210, 821, 431))
        self.scrollArea_12.setWidgetResizable(False)
        self.scrollArea_12.setObjectName("scrollArea_12")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 806, 800))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.scrollArea_12.setWidget(self.scrollAreaWidgetContents_8)
        self.searchButton_2 = QtWidgets.QPushButton(self.page_Comment)
        self.searchButton_2.setGeometry(QtCore.QRect(140, 230, 40, 20))
        self.searchButton_2.setStyleSheet("background-color: rgb(255, 255, 255，0);\n"
"border:none")
        self.searchButton_2.setText("")
        self.searchButton_2.setObjectName("searchButton_2")
        self.searchButton_6 = QtWidgets.QPushButton(self.page_Comment)
        self.searchButton_6.setGeometry(QtCore.QRect(140, 280, 40, 20))
        self.searchButton_6.setStyleSheet("background-color: rgb(255, 255, 255，0);\n"
"border:none")
        self.searchButton_6.setText("")
        self.searchButton_6.setObjectName("searchButton_6")
        self.stackedWidget.addWidget(self.page_Comment)
        self.menu_3 = QtWidgets.QFrame(self.background)
        self.menu_3.setGeometry(QtCore.QRect(40, 20, 481, 31))
        self.menu_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_3.setObjectName("menu_3")
        self.pushButton_releaseGame = QtWidgets.QPushButton(self.menu_3)
        self.pushButton_releaseGame.setGeometry(QtCore.QRect(90, 0, 91, 23))
        self.pushButton_releaseGame.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);  \n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"华光胖头鱼_CNKI\";\n"
"}")
        self.pushButton_releaseGame.setObjectName("pushButton_releaseGame")
        self.pushButton_HomePage = QtWidgets.QPushButton(self.menu_3)
        self.pushButton_HomePage.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.pushButton_HomePage.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);  \n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"华光胖头鱼_CNKI\";\n"
"}")
        self.pushButton_HomePage.setObjectName("pushButton_HomePage")
        ManufacturerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManufacturerWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.success_error_Type.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(ManufacturerWindow)

    def retranslateUi(self, ManufacturerWindow):
        _translate = QtCore.QCoreApplication.translate
        ManufacturerWindow.setWindowTitle(_translate("ManufacturerWindow", "MainWindow"))
        self.HPTitle.setText(_translate("ManufacturerWindow", "欢迎使用锅炉游戏管理平台"))
        self.lable_Title.setText(_translate("ManufacturerWindow", "以下是您的厂商信息"))
        self.lable_manufacturerID.setText(_translate("ManufacturerWindow", "厂商ID"))
        self.lable_manufacturerGameSum.setText(_translate("ManufacturerWindow", "游戏总数"))
        self.lineEdit_gameName.setPlaceholderText(_translate("ManufacturerWindow", "游戏名称："))
        self.lineEdit_gameType1.setPlaceholderText(_translate("ManufacturerWindow", "游戏类型3："))
        self.lineEdit_gamePrice.setPlaceholderText(_translate("ManufacturerWindow", "游戏售价："))
        self.lineEdit_gameType3.setPlaceholderText(_translate("ManufacturerWindow", "游戏类型1："))
        self.lineEdit_gameType2.setPlaceholderText(_translate("ManufacturerWindow", "游戏类型2："))
        self.lineEdit.setText(_translate("ManufacturerWindow", "简介："))
        self.label_2.setText(_translate("ManufacturerWindow", "在此处发布游戏"))
        self.pushButton_releaseSure.setText(_translate("ManufacturerWindow", "确认发布"))
        self.successRelease.setText(_translate("ManufacturerWindow", "发布成功"))
        self.successRelease_2.setText(_translate("ManufacturerWindow", "游戏信息未填写完整"))
        self.successRelease_3.setText(_translate("ManufacturerWindow", "有同名游戏"))
        self.successLogIn.setText(_translate("ManufacturerWindow", " 登陆成功"))
        self.successRegister.setText(_translate("ManufacturerWindow", " 注册成功"))
        self.logInWrong.setText(_translate("ManufacturerWindow", "用户名或密码错误"))
        self.sizeWrong.setText(_translate("ManufacturerWindow", "用户名或密码长度不符合要求"))
        self.userNameWrong.setText(_translate("ManufacturerWindow", "该用户名已存在"))
        self.passwordWrong.setText(_translate("ManufacturerWindow", "两次输入密码不一致"))
        self.label.setText(_translate("ManufacturerWindow", "在此页浏览你的游戏库"))
        self.pushButton_UnsetGames.setText(_translate("ManufacturerWindow", "未发布的游戏"))
        self.pushButton_SettedGames.setText(_translate("ManufacturerWindow", "已发布的游戏"))
        self.pushButton_AllGames.setText(_translate("ManufacturerWindow", "所有游戏"))
        self.searchline_2.setPlaceholderText(_translate("ManufacturerWindow", "搜索可发布的游戏"))
        self.label_5.setText(_translate("ManufacturerWindow", "在此页查询关注你的用户"))
        self.searchline_3.setPlaceholderText(_translate("ManufacturerWindow", "搜索用户的ID"))
        self.pushButton_FollowedUSR.setText(_translate("ManufacturerWindow", "被哪些用户关注"))
        self.pushButton_UnfollowedUSR.setText(_translate("ManufacturerWindow", "未被哪些用户关注"))
        self.label_8.setText(_translate("ManufacturerWindow", "在此页查询你的订单详情"))
        self.searchline_4.setPlaceholderText(_translate("ManufacturerWindow", "搜索订单的编号"))
        self.pushButton_PayList.setText(_translate("ManufacturerWindow", "付款订单"))
        self.pushButton_PaybackList.setText(_translate("ManufacturerWindow", "退款订单"))
        self.label_9.setText(_translate("ManufacturerWindow", "在此页查询你的用户评价"))
        self.searchline_Games.setPlaceholderText(_translate("ManufacturerWindow", "按游戏名查询"))
        self.searchline_Users.setPlaceholderText(_translate("ManufacturerWindow", "按用户名查询"))
        self.pushButton_releaseGame.setText(_translate("ManufacturerWindow", "游戏发布"))
        self.pushButton_HomePage.setText(_translate("ManufacturerWindow", "主页"))
import resgame_system_rc
