# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManufacturePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1030, 846)
        Dialog.setStyleSheet("background-color: rgb(59, 59, 99);")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(0, -10, 1031, 871))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1016, 856))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Home_Menu = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.Home_Menu.setGeometry(QtCore.QRect(30, -30, 951, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Home_Menu.sizePolicy().hasHeightForWidth())
        self.Home_Menu.setSizePolicy(sizePolicy)
        self.Home_Menu.setStyleSheet("background-color: rgb(9, 56, 117);")
        self.Home_Menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Home_Menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Home_Menu.setObjectName("Home_Menu")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(95, 400, 191, 421))
        self.listWidget.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.listWidget.setObjectName("listWidget")
        self.undoView_2 = QtWidgets.QUndoView(self.scrollAreaWidgetContents)
        self.undoView_2.setGeometry(QtCore.QRect(-470, 470, 791, 321))
        self.undoView_2.setStyleSheet("QWidget {\n"
"         background-color: rgba(0, 0, 0, 100);  \n"
"     }")
        self.undoView_2.setObjectName("undoView_2")
        self.undoView = QtWidgets.QUndoView(self.scrollAreaWidgetContents)
        self.undoView.setGeometry(QtCore.QRect(150, 170, 161, 161))
        self.undoView.setStyleSheet("border-radius: 80px;")
        self.undoView.setObjectName("undoView")
        self.listWidget_2 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget_2.setGeometry(QtCore.QRect(300, 400, 581, 421))
        self.listWidget_2.setStyleSheet("QWidget {\n"
"         background-color: rgba(0, 0, 0, 100);  \n"
"     }")
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(410, 330, 311, 31))
        self.label.setStyleSheet("font: 20pt \"华文琥珀\";\n"
"background-color: rgb(255, 255, 255，100);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(111, 462, 151, 23))
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(111, 582, 151, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(111, 642, 151, 23))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(111, 522, 151, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_2.raise_()
        self.undoView_2.raise_()
        self.Home_Menu.raise_()
        self.undoView.raise_()
        self.listWidget_2.raise_()
        self.label.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "在此处管理厂商的操作"))
        self.pushButton.setText(_translate("Dialog", "厂商资料"))
        self.pushButton_3.setText(_translate("Dialog", "发售的游戏"))
        self.pushButton_4.setText(_translate("Dialog", "查询订单信息"))
        self.pushButton_2.setText(_translate("Dialog", "关注用户列表"))
