# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testshoplist.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 100)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 565, 100))
        self.frame_9.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushButton = QtWidgets.QPushButton(self.frame_9)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 400, 50))
        self.pushButton.setStyleSheet("background-color: rgb(59, 59, 100,0);\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_ShowPrice = QtWidgets.QLabel(self.frame_9)
        self.label_ShowPrice.setGeometry(QtCore.QRect(483, 50, 71, 20))
        self.label_ShowPrice.setStyleSheet("background-color: rgb(59, 59, 100,0);\n"
"")
        self.label_ShowPrice.setText("")
        self.label_ShowPrice.setObjectName("label_ShowPrice")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_2.setGeometry(QtCore.QRect(484, 73, 71, 20))
        self.pushButton_2.setStyleSheet("background-color: rgb(59, 59, 100,0);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "删除"))
import resgame_system_rc
