# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testfriendpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_Friend = QtWidgets.QFrame(self.centralwidget)
        self.frame_Friend.setGeometry(QtCore.QRect(0, 0, 250, 80))
        self.frame_Friend.setStyleSheet("background-color: rgb(128, 134, 255);")
        self.frame_Friend.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Friend.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Friend.setObjectName("frame_Friend")
        self.pushButton_Friend = QtWidgets.QPushButton(self.frame_Friend)
        self.pushButton_Friend.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.pushButton_Friend.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/u=772358879,2131786806&fm=253&fmt=auto&app=138&f=JPEG.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Friend.setIcon(icon)
        self.pushButton_Friend.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_Friend.setObjectName("pushButton_Friend")
        self.label_FriendName = QtWidgets.QLabel(self.frame_Friend)
        self.label_FriendName.setGeometry(QtCore.QRect(90, 30, 141, 21))
        self.label_FriendName.setObjectName("label_FriendName")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_FriendName.setText(_translate("MainWindow", "TextLabel"))
import resgame_system_rc
