# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_testwindow(object):
    def setupUi(self, testwindow):
        testwindow.setObjectName("testwindow")
        testwindow.resize(1022, 768)
        self.centralwidget = QtWidgets.QWidget(testwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.background.setMinimumSize(QtCore.QSize(801, 571))
        self.background.setStyleSheet("#background{\n"
"border-radius:7px;\n"
"background-color: rgb(38, 38, 38);\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.background)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu = QtWidgets.QFrame(self.background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.pushButton_GoMainPage = QtWidgets.QPushButton(self.menu)
        self.pushButton_GoMainPage.setGeometry(QtCore.QRect(60, 10, 61, 31))
        self.pushButton_GoMainPage.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);  \n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"华光胖头鱼_CNKI\";\n"
"}")
        self.pushButton_GoMainPage.setObjectName("pushButton_GoMainPage")
        self.pushButton_GoPersonalPage = QtWidgets.QPushButton(self.menu)
        self.pushButton_GoPersonalPage.setGeometry(QtCore.QRect(940, 10, 61, 31))
        self.pushButton_GoPersonalPage.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);  \n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"黑体\";\n"
"}")
        self.pushButton_GoPersonalPage.setText("")
        self.pushButton_GoPersonalPage.setObjectName("pushButton_GoPersonalPage")
        self.pushButton_GoGameLibraryPage = QtWidgets.QPushButton(self.menu)
        self.pushButton_GoGameLibraryPage.setGeometry(QtCore.QRect(130, 10, 61, 31))
        self.pushButton_GoGameLibraryPage.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);  \n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"华光胖头鱼_CNKI\";\n"
"}")
        self.pushButton_GoGameLibraryPage.setObjectName("pushButton_GoGameLibraryPage")
        self.pushButton_GoShoppingCartPage = QtWidgets.QPushButton(self.menu)
        self.pushButton_GoShoppingCartPage.setGeometry(QtCore.QRect(200, 10, 61, 31))
        self.pushButton_GoShoppingCartPage.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);  \n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"华光胖头鱼_CNKI\";\n"
"}")
        self.pushButton_GoShoppingCartPage.setObjectName("pushButton_GoShoppingCartPage")
        self.pushButton_GoFriendPage = QtWidgets.QPushButton(self.menu)
        self.pushButton_GoFriendPage.setGeometry(QtCore.QRect(280, 10, 61, 31))
        self.pushButton_GoFriendPage.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);  \n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"华光胖头鱼_CNKI\";\n"
"}")
        self.pushButton_GoFriendPage.setObjectName("pushButton_GoFriendPage")
        self.verticalLayout.addWidget(self.menu)
        self.main = QtWidgets.QFrame(self.background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setStyleSheet("background-color: rgb(59, 59, 89);")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget_Window = QtWidgets.QStackedWidget(self.main)
        self.stackedWidget_Window.setObjectName("stackedWidget_Window")
        self.page_MainWindow = QtWidgets.QWidget()
        self.page_MainWindow.setObjectName("page_MainWindow")
        self.scrollArea = QtWidgets.QScrollArea(self.page_MainWindow)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1024, 640))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(781, 454))
        self.scrollArea.setStyleSheet("QProgressBar{\n"
"background-color: white; \n"
"border: 1px solid black;\n"
"}")
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1009, 10000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(766, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1009, 171))
        self.frame_3.setMinimumSize(QtCore.QSize(771, 120))
        self.frame_3.setStyleSheet("background-color: rgb(101, 222, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(290, 10, 661, 41))
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgb(59, 59, 89,0.5);\n"
"border-radius:15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_SearchGame = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_SearchGame.setGeometry(QtCore.QRect(470, 10, 160, 20))
        self.lineEdit_SearchGame.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);\n"
"    border: none;")
        self.lineEdit_SearchGame.setObjectName("lineEdit_SearchGame")
        self.pushButton_SearchGame = QtWidgets.QPushButton(self.frame)
        self.pushButton_SearchGame.setGeometry(QtCore.QRect(590, 10, 40, 20))
        self.pushButton_SearchGame.setStyleSheet("background-color: rgb(255, 255, 255，0);\n"
"border:none")
        self.pushButton_SearchGame.setText("")
        self.pushButton_SearchGame.setObjectName("pushButton_SearchGame")
        self.label_picture = QtWidgets.QLabel(self.frame_3)
        self.label_picture.setGeometry(QtCore.QRect(0, 0, 1024, 171))
        self.label_picture.setLineWidth(1)
        self.label_picture.setText("")
        self.label_picture.setPixmap(QtGui.QPixmap(":/icon/QQ图片20240607103720.jpg"))
        self.label_picture.setObjectName("label_picture")
        self.label_picture.raise_()
        self.frame.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_Window.addWidget(self.page_MainWindow)
        self.page_SearchPage = QtWidgets.QWidget()
        self.page_SearchPage.setObjectName("page_SearchPage")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_SearchPage)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 1024, 640))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(781, 454))
        self.scrollArea_2.setStyleSheet("QProgressBar{\n"
"background-color: white; \n"
"border: 1px solid black;\n"
"}")
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1009, 1000))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(766, 0))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1011, 171))
        self.frame_4.setMinimumSize(QtCore.QSize(771, 120))
        self.frame_4.setStyleSheet("background-color: rgb(101, 222, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(290, 10, 661, 41))
        self.frame_2.setStyleSheet("#frame{\n"
"background-color: rgb(59, 59, 89,0.2);\n"
"border-radius:15px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_picture_2 = QtWidgets.QLabel(self.frame_4)
        self.label_picture_2.setGeometry(QtCore.QRect(0, 0, 1024, 171))
        self.label_picture_2.setLineWidth(1)
        self.label_picture_2.setText("")
        self.label_picture_2.setPixmap(QtGui.QPixmap(":/icon/QQ图片20240607104332.jpg"))
        self.label_picture_2.setObjectName("label_picture_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.stackedWidget_Window.addWidget(self.page_SearchPage)
        self.page_PersonalFriendPage = QtWidgets.QWidget()
        self.page_PersonalFriendPage.setObjectName("page_PersonalFriendPage")
        self.frame_8 = QtWidgets.QFrame(self.page_PersonalFriendPage)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 1024, 640))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1024, 180))
        self.frame_6.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/u=157358869,2307745509&fm=217&app=126&size=f242,150&n=0&f=PNG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(320, 320))
        self.pushButton.setObjectName("pushButton")
        self.label_Show_UserName = QtWidgets.QLabel(self.frame_6)
        self.label_Show_UserName.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_UserName.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_UserName.setText("")
        self.label_Show_UserName.setObjectName("label_Show_UserName")
        self.listWidget = QtWidgets.QListWidget(self.frame_8)
        self.listWidget.setGeometry(QtCore.QRect(10, 210, 190, 200))
        self.listWidget.setStyleSheet("background-color: rgba(0, 0, 0, 100);  \n"
"border: none")
        self.listWidget.setObjectName("listWidget")
        self.pushButton_ShowApplication = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_ShowApplication.setGeometry(QtCore.QRect(30, 310, 151, 23))
        self.pushButton_ShowApplication.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_ShowApplication.setObjectName("pushButton_ShowApplication")
        self.pushButton_ShowAddFriend = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_ShowAddFriend.setGeometry(QtCore.QRect(30, 270, 151, 23))
        self.pushButton_ShowAddFriend.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_ShowAddFriend.setObjectName("pushButton_ShowAddFriend")
        self.pushButton_ShowUserFriends = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_ShowUserFriends.setGeometry(QtCore.QRect(30, 230, 151, 23))
        self.pushButton_ShowUserFriends.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_ShowUserFriends.setObjectName("pushButton_ShowUserFriends")
        self.stackedWidget_userFriendPage = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget_userFriendPage.setGeometry(QtCore.QRect(200, 210, 800, 420))
        self.stackedWidget_userFriendPage.setObjectName("stackedWidget_userFriendPage")
        self.page_userfriend = QtWidgets.QWidget()
        self.page_userfriend.setObjectName("page_userfriend")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_userfriend)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 0, 800, 420))
        self.scrollArea_3.setStyleSheet("border:none\n"
"")
        self.scrollArea_3.setWidgetResizable(False)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 787, 1000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget_userFriendPage.addWidget(self.page_userfriend)
        self.page_addfriend = QtWidgets.QWidget()
        self.page_addfriend.setObjectName("page_addfriend")
        self.frame_14 = QtWidgets.QFrame(self.page_addfriend)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 800, 420))
        self.frame_14.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.lineEdit_addSearchName = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_addSearchName.setGeometry(QtCore.QRect(60, 20, 521, 40))
        self.lineEdit_addSearchName.setStyleSheet("background-color: rgb(255, 255, 255,80);\n"
"color: rgb(255, 255, 255);\n"
"border: none")
        self.lineEdit_addSearchName.setText("")
        self.lineEdit_addSearchName.setObjectName("lineEdit_addSearchName")
        self.pushButton_search = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_search.setGeometry(QtCore.QRect(600, 20, 100, 40))
        self.pushButton_search.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_search.setObjectName("pushButton_search")
        self.frame_showSearchedPage = QtWidgets.QFrame(self.frame_14)
        self.frame_showSearchedPage.setGeometry(QtCore.QRect(60, 90, 640, 300))
        self.frame_showSearchedPage.setStyleSheet("background-color: rgb(255, 255, 255,0.4);")
        self.frame_showSearchedPage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_showSearchedPage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_showSearchedPage.setObjectName("frame_showSearchedPage")
        self.stackedWidget_userFriendPage.addWidget(self.page_addfriend)
        self.page_application = QtWidgets.QWidget()
        self.page_application.setObjectName("page_application")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.page_application)
        self.scrollArea_6.setGeometry(QtCore.QRect(0, 0, 800, 420))
        self.scrollArea_6.setStyleSheet("border:none\n"
"")
        self.scrollArea_6.setWidgetResizable(False)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_applicationUser = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_applicationUser.setGeometry(QtCore.QRect(0, 0, 787, 1000))
        self.scrollAreaWidgetContents_applicationUser.setObjectName("scrollAreaWidgetContents_applicationUser")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_applicationUser)
        self.stackedWidget_userFriendPage.addWidget(self.page_application)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_userFriendPage.addWidget(self.page_2)
        self.stackedWidget_Window.addWidget(self.page_PersonalFriendPage)
        self.page_FriendPage = QtWidgets.QWidget()
        self.page_FriendPage.setObjectName("page_FriendPage")
        self.frame_7 = QtWidgets.QFrame(self.page_FriendPage)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1022, 180))
        self.frame_7.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_Friend = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Friend.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton_Friend.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton_Friend.setText("")
        self.pushButton_Friend.setIcon(icon)
        self.pushButton_Friend.setIconSize(QtCore.QSize(320, 320))
        self.pushButton_Friend.setObjectName("pushButton_Friend")
        self.label_Show_FriendName = QtWidgets.QLabel(self.frame_7)
        self.label_Show_FriendName.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_FriendName.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_FriendName.setText("")
        self.label_Show_FriendName.setObjectName("label_Show_FriendName")
        self.stackedWidget_Window.addWidget(self.page_FriendPage)
        self.page_PersonalGameLibraryPage = QtWidgets.QWidget()
        self.page_PersonalGameLibraryPage.setObjectName("page_PersonalGameLibraryPage")
        self.frame_11 = QtWidgets.QFrame(self.page_PersonalGameLibraryPage)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 1024, 640))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 1022, 180))
        self.frame_12.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton_4.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(320, 320))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_Show_UserName_2 = QtWidgets.QLabel(self.frame_12)
        self.label_Show_UserName_2.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_UserName_2.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_UserName_2.setText("")
        self.label_Show_UserName_2.setObjectName("label_Show_UserName_2")
        self.Classify_Frame_2 = QtWidgets.QFrame(self.frame_11)
        self.Classify_Frame_2.setGeometry(QtCore.QRect(111, 190, 800, 40))
        self.Classify_Frame_2.setStyleSheet("QWidget {\n"
"         background-color:rgb(64, 100, 167);  \n"
"     }")
        self.Classify_Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Classify_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Classify_Frame_2.setObjectName("Classify_Frame_2")
        self.Search_Bar = QtWidgets.QLineEdit(self.Classify_Frame_2)
        self.Search_Bar.setGeometry(QtCore.QRect(320, 10, 161, 20))
        self.Search_Bar.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);\n"
"    border: none;")
        self.Search_Bar.setObjectName("Search_Bar")
        self.frame_5 = QtWidgets.QFrame(self.frame_11)
        self.frame_5.setGeometry(QtCore.QRect(350, 250, 561, 360))
        self.frame_5.setStyleSheet("background-color: rgb(59, 59, 99);\n"
"border: none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea_5.setGeometry(QtCore.QRect(0, 0, 561, 361))
        self.scrollArea_5.setStyleSheet("")
        self.scrollArea_5.setWidgetResizable(False)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_GameLibrary = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_GameLibrary.setGeometry(QtCore.QRect(0, 0, 546, 1000))
        self.scrollAreaWidgetContents_GameLibrary.setObjectName("scrollAreaWidgetContents_GameLibrary")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_GameLibrary)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setGeometry(QtCore.QRect(111, 250, 200, 360))
        self.frame_13.setStyleSheet("QWidget {\n"
"         background-color:rgb(64, 100, 167);  \n"
"     }")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_4 = QtWidgets.QLabel(self.frame_13)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 61, 31))
        self.label_4.setStyleSheet("font: 9pt \"华文琥珀\";\n"
"background-color: rgb(255, 255, 255，100);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_13)
        self.listWidget_3.setGeometry(QtCore.QRect(30, 50, 141, 192))
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.stackedWidget_Window.addWidget(self.page_PersonalGameLibraryPage)
        self.page_PersonalShoppinCartPage = QtWidgets.QWidget()
        self.page_PersonalShoppinCartPage.setObjectName("page_PersonalShoppinCartPage")
        self.frame_10 = QtWidgets.QFrame(self.page_PersonalShoppinCartPage)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 1021, 641))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_20 = QtWidgets.QFrame(self.frame_10)
        self.frame_20.setGeometry(QtCore.QRect(0, 0, 1031, 181))
        self.frame_20.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton_7.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(320, 320))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_Show_UserName_3 = QtWidgets.QLabel(self.frame_20)
        self.label_Show_UserName_3.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_UserName_3.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_UserName_3.setText("")
        self.label_Show_UserName_3.setObjectName("label_Show_UserName_3")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setGeometry(QtCore.QRect(40, 200, 331, 31))
        self.label_6.setStyleSheet("font: 20pt \"华文琥珀\";\n"
"background-color: rgb(255, 255, 255，100);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.scrollArea_9 = QtWidgets.QScrollArea(self.frame_10)
        self.scrollArea_9.setGeometry(QtCore.QRect(40, 250, 670, 360))
        self.scrollArea_9.setWidgetResizable(False)
        self.scrollArea_9.setObjectName("scrollArea_9")
        self.scrollAreaWidgetContents_Shoppingcart = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_Shoppingcart.setGeometry(QtCore.QRect(0, 0, 655, 1000))
        self.scrollAreaWidgetContents_Shoppingcart.setObjectName("scrollAreaWidgetContents_Shoppingcart")
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_Shoppingcart)
        self.Classify_Frame_4 = QtWidgets.QFrame(self.frame_10)
        self.Classify_Frame_4.setGeometry(QtCore.QRect(750, 250, 241, 180))
        self.Classify_Frame_4.setStyleSheet("QWidget {\n"
"         background-color:rgb(64, 100, 167);  \n"
"     }")
        self.Classify_Frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Classify_Frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Classify_Frame_4.setObjectName("Classify_Frame_4")
        self.label_7 = QtWidgets.QLabel(self.Classify_Frame_4)
        self.label_7.setGeometry(QtCore.QRect(40, 20, 101, 31))
        self.label_7.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(255, 255, 255，100);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.pushButton_Pay = QtWidgets.QPushButton(self.Classify_Frame_4)
        self.pushButton_Pay.setGeometry(QtCore.QRect(40, 130, 171, 31))
        self.pushButton_Pay.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_Pay.setObjectName("pushButton_Pay")
        self.pushButton_KeepShopping = QtWidgets.QPushButton(self.Classify_Frame_4)
        self.pushButton_KeepShopping.setGeometry(QtCore.QRect(40, 90, 171, 31))
        self.pushButton_KeepShopping.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_KeepShopping.setObjectName("pushButton_KeepShopping")
        self.label_showAllPrice = QtWidgets.QLabel(self.Classify_Frame_4)
        self.label_showAllPrice.setGeometry(QtCore.QRect(150, 20, 54, 31))
        self.label_showAllPrice.setText("")
        self.label_showAllPrice.setObjectName("label_showAllPrice")
        self.stackedWidget_Window.addWidget(self.page_PersonalShoppinCartPage)
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.frame_9 = QtWidgets.QFrame(self.widget)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 1024, 180))
        self.frame_9.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushButton_Friend_2 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_Friend_2.setGeometry(QtCore.QRect(20, 10, 160, 160))
        self.pushButton_Friend_2.setStyleSheet("border-radius: 80px;\n"
"    background-color: rgba(0, 0, 0, 0);  ")
        self.pushButton_Friend_2.setText("")
        self.pushButton_Friend_2.setIcon(icon)
        self.pushButton_Friend_2.setIconSize(QtCore.QSize(320, 320))
        self.pushButton_Friend_2.setObjectName("pushButton_Friend_2")
        self.label_Show_FriendName_2 = QtWidgets.QLabel(self.frame_9)
        self.label_Show_FriendName_2.setGeometry(QtCore.QRect(193, 59, 581, 71))
        self.label_Show_FriendName_2.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  \n"
"font: 40pt \"华光胖头鱼_CNKI\";")
        self.label_Show_FriendName_2.setText("")
        self.label_Show_FriendName_2.setObjectName("label_Show_FriendName_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 331, 31))
        self.label_2.setStyleSheet("font: 20pt \"华文琥珀\";\n"
"background-color: rgb(255, 255, 255，100);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.widget)
        self.scrollArea_4.setGeometry(QtCore.QRect(40, 250, 600, 361))
        self.scrollArea_4.setWidgetResizable(False)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 585, 800))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.Classify_Frame = QtWidgets.QFrame(self.widget)
        self.Classify_Frame.setGeometry(QtCore.QRect(700, 250, 311, 181))
        self.Classify_Frame.setStyleSheet("QWidget {\n"
"         background-color:rgb(64, 100, 167);  \n"
"     }")
        self.Classify_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Classify_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Classify_Frame.setObjectName("Classify_Frame")
        self.label_3 = QtWidgets.QLabel(self.Classify_Frame)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 101, 31))
        self.label_3.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"background-color: rgb(255, 255, 255，100);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.Classify_Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 130, 171, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Classify_Frame)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 90, 171, 31))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget_Window.addWidget(self.widget)
        self.page_evaluateGame = QtWidgets.QWidget()
        self.page_evaluateGame.setObjectName("page_evaluateGame")
        self.frame_15 = QtWidgets.QFrame(self.page_evaluateGame)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 1024, 100))
        self.frame_15.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_show_gameName = QtWidgets.QLabel(self.frame_15)
        self.label_show_gameName.setGeometry(QtCore.QRect(25, 25, 400, 50))
        self.label_show_gameName.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 30pt \"宋体\";\n"
"color: rgb(255, 255, 255);")
        self.label_show_gameName.setText("")
        self.label_show_gameName.setObjectName("label_show_gameName")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.page_evaluateGame)
        self.scrollArea_7.setGeometry(QtCore.QRect(0, 100, 1022, 541))
        self.scrollArea_7.setWidgetResizable(False)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1007, 10000))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.textEdit_gameIntroduction = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit_gameIntroduction.setGeometry(QtCore.QRect(53, 20, 900, 150))
        self.textEdit_gameIntroduction.setStyleSheet("background-color: rgba(0, 0, 0, 100);  \n"
"border: none\n"
"     ")
        self.textEdit_gameIntroduction.setObjectName("textEdit_gameIntroduction")
        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_16.setGeometry(QtCore.QRect(53, 190, 900, 350))
        self.frame_16.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255,80);\n"
"border: none\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255,80);\n"
"border: none\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.textEdit_evaluate = QtWidgets.QTextEdit(self.frame_16)
        self.textEdit_evaluate.setGeometry(QtCore.QRect(70, 70, 760, 200))
        self.textEdit_evaluate.setObjectName("textEdit_evaluate")
        self.lineEdit_writeForWhichGame = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_writeForWhichGame.setGeometry(QtCore.QRect(70, 40, 760, 30))
        self.lineEdit_writeForWhichGame.setText("")
        self.lineEdit_writeForWhichGame.setReadOnly(True)
        self.lineEdit_writeForWhichGame.setObjectName("lineEdit_writeForWhichGame")
        self.pushButton_postSure = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_postSure.setGeometry(QtCore.QRect(660, 280, 171, 30))
        self.pushButton_postSure.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_postSure.setObjectName("pushButton_postSure")
        self.pushButton_recommend = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_recommend.setGeometry(QtCore.QRect(160, 280, 31, 30))
        self.pushButton_recommend.setStyleSheet("font: 9pt \"华光胖头鱼_CNKI\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_recommend.setObjectName("pushButton_recommend")
        self.pushButton_disrecommend = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_disrecommend.setGeometry(QtCore.QRect(200, 280, 31, 30))
        self.pushButton_disrecommend.setStyleSheet("font: 9pt \"华光胖头鱼_CNKI\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_disrecommend.setObjectName("pushButton_disrecommend")
        self.lable_manufacturerID = QtWidgets.QLabel(self.frame_16)
        self.lable_manufacturerID.setGeometry(QtCore.QRect(70, 280, 81, 30))
        self.lable_manufacturerID.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"华文仿宋\";\n"
"")
        self.lable_manufacturerID.setObjectName("lable_manufacturerID")
        self.success_error_Type = QtWidgets.QStackedWidget(self.frame_16)
        self.success_error_Type.setGeometry(QtCore.QRect(720, 310, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.success_error_Type.sizePolicy().hasHeightForWidth())
        self.success_error_Type.setSizePolicy(sizePolicy)
        self.success_error_Type.setStyleSheet("#successLogIn{\n"
"}\n"
"#successRegister{\n"
"}\n"
"#sizeWrong{\n"
"    color: rgb(190, 0, 0);\n"
"}\n"
"#userNameWrong{\n"
"    color: rgb(190, 0, 0);\n"
"}\n"
"#passwordWrong{\n"
"    color: rgb(190, 0, 0);\n"
"}\n"
"#logInWrong{\n"
"    color: rgb(190, 0, 0);\n"
"}")
        self.success_error_Type.setObjectName("success_error_Type")
        self.emptyPage = QtWidgets.QWidget()
        self.emptyPage.setObjectName("emptyPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.emptyPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.success_error_Type.addWidget(self.emptyPage)
        self.page_success = QtWidgets.QWidget()
        self.page_success.setObjectName("page_success")
        self.successRelease = QtWidgets.QLabel(self.page_success)
        self.successRelease.setGeometry(QtCore.QRect(0, 10, 54, 12))
        self.successRelease.setStyleSheet("color: rgb(255, 255, 255);")
        self.successRelease.setObjectName("successRelease")
        self.success_error_Type.addWidget(self.page_success)
        self.page_error1 = QtWidgets.QWidget()
        self.page_error1.setObjectName("page_error1")
        self.successRelease_2 = QtWidgets.QLabel(self.page_error1)
        self.successRelease_2.setGeometry(QtCore.QRect(0, 10, 51, 16))
        self.successRelease_2.setStyleSheet("color: rgb(190, 0, 0);")
        self.successRelease_2.setObjectName("successRelease_2")
        self.success_error_Type.addWidget(self.page_error1)
        self.page_error2 = QtWidgets.QWidget()
        self.page_error2.setObjectName("page_error2")
        self.successRelease_3 = QtWidgets.QLabel(self.page_error2)
        self.successRelease_3.setGeometry(QtCore.QRect(0, 10, 61, 16))
        self.successRelease_3.setStyleSheet("color: rgb(190, 0, 0);")
        self.successRelease_3.setObjectName("successRelease_3")
        self.success_error_Type.addWidget(self.page_error2)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout = QtWidgets.QGridLayout(self.page1)
        self.gridLayout.setObjectName("gridLayout")
        self.successLogIn = QtWidgets.QLabel(self.page1)
        self.successLogIn.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.successLogIn.setObjectName("successLogIn")
        self.gridLayout.addWidget(self.successLogIn, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.successRegister = QtWidgets.QLabel(self.page2)
        self.successRegister.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.successRegister.setObjectName("successRegister")
        self.horizontalLayout_3.addWidget(self.successRegister, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.logInWrong = QtWidgets.QLabel(self.page3)
        self.logInWrong.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.logInWrong.setObjectName("logInWrong")
        self.verticalLayout_7.addWidget(self.logInWrong, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sizeWrong = QtWidgets.QLabel(self.page4)
        self.sizeWrong.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.sizeWrong.setObjectName("sizeWrong")
        self.verticalLayout_9.addWidget(self.sizeWrong, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.userNameWrong = QtWidgets.QLabel(self.page5)
        self.userNameWrong.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.userNameWrong.setObjectName("userNameWrong")
        self.verticalLayout_10.addWidget(self.userNameWrong, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page5)
        self.page6 = QtWidgets.QWidget()
        self.page6.setObjectName("page6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.passwordWrong = QtWidgets.QLabel(self.page6)
        self.passwordWrong.setStyleSheet("#userNameWrong_1{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.passwordWrong.setObjectName("passwordWrong")
        self.verticalLayout_11.addWidget(self.passwordWrong, 0, QtCore.Qt.AlignHCenter)
        self.success_error_Type.addWidget(self.page6)
        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_17.setGeometry(QtCore.QRect(50, 660, 901, 81))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.lineEdit_writeForWhichGame_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_writeForWhichGame_2.setGeometry(QtCore.QRect(53, 570, 900, 30))
        self.lineEdit_writeForWhichGame_2.setStyleSheet("QLineEdit{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"华文仿宋\";\n"
"background-color: rgb(255, 255, 255,80);\n"
"border: none\n"
"}\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"华文仿宋\";\n"
"")
        self.lineEdit_writeForWhichGame_2.setReadOnly(True)
        self.lineEdit_writeForWhichGame_2.setObjectName("lineEdit_writeForWhichGame_2")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_5)
        self.stackedWidget_Window.addWidget(self.page_evaluateGame)
        self.horizontalLayout.addWidget(self.stackedWidget_Window)
        self.verticalLayout.addWidget(self.main)
        self.menu_2 = QtWidgets.QFrame(self.background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.menu_2.sizePolicy().hasHeightForWidth())
        self.menu_2.setSizePolicy(sizePolicy)
        self.menu_2.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.menu_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_2.setObjectName("menu_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.menu_2)
        self.textBrowser.setGeometry(QtCore.QRect(770, 10, 221, 41))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"border:none;\n"
"border-radius:10px;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.menu_2)
        testwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(testwindow)
        self.stackedWidget_Window.setCurrentIndex(0)
        self.success_error_Type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(testwindow)

    def retranslateUi(self, testwindow):
        _translate = QtCore.QCoreApplication.translate
        testwindow.setWindowTitle(_translate("testwindow", "MainWindow"))
        self.pushButton_GoMainPage.setText(_translate("testwindow", "商店"))
        self.pushButton_GoGameLibraryPage.setText(_translate("testwindow", "库"))
        self.pushButton_GoShoppingCartPage.setText(_translate("testwindow", "购物车"))
        self.pushButton_GoFriendPage.setText(_translate("testwindow", "好友"))
        self.lineEdit_SearchGame.setPlaceholderText(_translate("testwindow", "搜索"))
        self.pushButton_ShowApplication.setText(_translate("testwindow", "待处理申请"))
        self.pushButton_ShowAddFriend.setText(_translate("testwindow", "添加好友"))
        self.pushButton_ShowUserFriends.setText(_translate("testwindow", "我的好友"))
        self.lineEdit_addSearchName.setPlaceholderText(_translate("testwindow", "在此输入好友昵称："))
        self.pushButton_search.setText(_translate("testwindow", "查找"))
        self.Search_Bar.setPlaceholderText(_translate("testwindow", "搜索已有的游戏名"))
        self.label_4.setText(_translate("testwindow", "按类型筛选"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("testwindow", "开放世界"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("testwindow", "MOBA"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("testwindow", "塔防"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("testwindow", "您的购物车"))
        self.label_7.setText(_translate("testwindow", "预计总额："))
        self.pushButton_Pay.setText(_translate("testwindow", "支付"))
        self.pushButton_KeepShopping.setText(_translate("testwindow", "继续购物"))
        self.label_2.setText(_translate("testwindow", "您的购物车"))
        self.label_3.setText(_translate("testwindow", "预计总额："))
        self.pushButton_2.setText(_translate("testwindow", "支付"))
        self.pushButton_3.setText(_translate("testwindow", "继续购物"))
        self.pushButton_postSure.setText(_translate("testwindow", "确认发布"))
        self.pushButton_recommend.setText(_translate("testwindow", "Y"))
        self.pushButton_disrecommend.setText(_translate("testwindow", "N"))
        self.lable_manufacturerID.setText(_translate("testwindow", "是否推荐："))
        self.successRelease.setText(_translate("testwindow", "发布成功"))
        self.successRelease_2.setText(_translate("testwindow", "出现错误"))
        self.successRelease_3.setText(_translate("testwindow", "发布成功"))
        self.successLogIn.setText(_translate("testwindow", " 登陆成功"))
        self.successRegister.setText(_translate("testwindow", " 注册成功"))
        self.logInWrong.setText(_translate("testwindow", "用户名或密码错误"))
        self.sizeWrong.setText(_translate("testwindow", "用户名或密码长度不符合要求"))
        self.userNameWrong.setText(_translate("testwindow", "该用户名已存在"))
        self.passwordWrong.setText(_translate("testwindow", "两次输入密码不一致"))
        self.lineEdit_writeForWhichGame_2.setText(_translate("testwindow", "其他用户对该游戏的评价："))
        self.textBrowser.setHtml(_translate("testwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">开发者姓名：               胡植淮</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">   学号：            202200800014</span></p></body></html>"))
import resgame_system_rc
