# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testgamelablepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 70)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 506, 70))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 100);  ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Game_Name = QtWidgets.QLabel(self.frame)
        self.Game_Name.setGeometry(QtCore.QRect(3, 3, 500, 30))
        self.Game_Name.setMouseTracking(True)
        self.Game_Name.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255,60);\n"
"    font: 15pt \"微软雅黑\";\n"
"    color: rgb(255, 255, 255);\n"
"     }\n"
"")
        self.Game_Name.setText("")
        self.Game_Name.setObjectName("Game_Name")
        self.pushButton_Evaluate = QtWidgets.QPushButton(self.frame)
        self.pushButton_Evaluate.setGeometry(QtCore.QRect(340, 40, 75, 23))
        self.pushButton_Evaluate.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_Evaluate.setObjectName("pushButton_Evaluate")
        self.pushButton_StartGame = QtWidgets.QPushButton(self.frame)
        self.pushButton_StartGame.setGeometry(QtCore.QRect(420, 40, 75, 23))
        self.pushButton_StartGame.setStyleSheet("QPushButton {\n"
"         background-color: rgb(154, 231, 231);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_StartGame.setObjectName("pushButton_StartGame")
        self.pushButton_Remove = QtWidgets.QPushButton(self.frame)
        self.pushButton_Remove.setGeometry(QtCore.QRect(260, 40, 75, 23))
        self.pushButton_Remove.setStyleSheet("QPushButton {\n"
"         background-color: rgb(92, 138, 0);\n"
"    color: rgb(255, 255, 255);\n"
"     }")
        self.pushButton_Remove.setObjectName("pushButton_Remove")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Evaluate.setText(_translate("MainWindow", "评价"))
        self.pushButton_StartGame.setText(_translate("MainWindow", "开始游戏"))
        self.pushButton_Remove.setText(_translate("MainWindow", "退款"))
